services:
  db:
    image: postgres:15
    container_name: tokenindexer-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: tokenindexer-app
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "3000:3000" # 포트는 필요에 따라 조정
    volumes:
      - .:/app
    command: ["node", "src/index.js"]

volumes:
  pgdata:
